default:
  packages: "GlobalScripts/packages.R"
  setup: "GlobalScripts/global_setup.R"
  set_paths: "GlobalScripts/set_paths.R"
  conflicts: "GlobalScripts/conflicts.R"
  functions: "GlobalScripts/functions.R"
  fonts: "GlobalScripts/fonts/FA6_Free-Solid-900.otf"
  
libprep:
  app: "LibraryPrep/app.R"
  colDefs: "LibraryPrep/colDefs.R"
  materials: "LibraryPrep/materials.R"
  list_protocols: "LibraryPrep/list_protocols.R"
  protocol_modules: "LibraryPrep/protocol_modules.R"
  setupModule: "LibraryPrep/setupModule.R"
  images: "LibraryPrep/images/"
  samples:
    loris: "sample_inventories/compilation_loris.tsv"
    marmoset: "sample_inventories/compilation_marmoset.tsv"
    bats: "sample_inventories/compilation_bats.tsv"
    isolates: "sample_inventories/compilation_isolates.tsv"
    envir: "sample_inventories/compilation_envir.tsv"
  
rapid16s:
  man_protocol: "ProtocolSummaries/man_protocols/rapid16s.pdf"
  summary: "ProtocolSummaries/rapid16s_workflow_steps.html"

lsk:
  man_protocol: "ProtocolSummaries/man_protocols/lsk.pdf"
  summary: "ProtocolSummaries/lsk_workflow_steps.html"
  
notebooks:
  AMR: "Notebooks/Rich/"
  SA: "Notebooks/Azadmanesh/"
  TA: "Notebooks/Raad/"
  TSP: "Notebooks/Palacio/"
  DG: "Notebooks/Gill/"