default:
  packages: "setup/packages.R"
  setup: "setup/setup.R"
  conflicts: "setup/conflicts.R"
  functions: "setup/functions.R"
  inputs: "setup/inputs.R"
  fonts: "setup/fonts/FA6_Free-Solid-900.otf"
  
budget:
  scripts: !expr list("supplies/consumables_byFY.R", "supplies/travel_byFY.R", "supplies/personnel_byFY.R", "supplies/equipment_byFY.R", "supplies/projects_byFY.R", "supplies/budget_summary.R")
  table: "supplies/budget_byFY.tsv"
  html: "supplies/budget_byFY.html"
  
libprep:
  app: "LibraryPrep/app.R"
  colDefs: "LibraryPrep/colDefs.R"
  materials: "LibraryPrep/materials.R"
  list_protocols: "LibraryPrep/list_protocols.R"
  protocol_modules: "LibraryPrep/protocol_modules.R"
  setupModule: "LibraryPrep/setupModule.R"
  images: "LibraryPrep/images/"
  samples:
    loris: "../bioinformatics_stats/dataframes/sample_inventories/compilation_loris.tsv"
    marmoset: "../bioinformatics_stats/dataframes/sample_inventories/compilation_marmoset.tsv"
    bats: "../bioinformatics_stats/dataframes/sample_inventories/compilation_bats.tsv"
    isolates: "../bioinformatics_stats/dataframes/sample_inventories/compilation_isolates.tsv"
    envir: "../bioinformatics_stats/dataframes/sample_inventories/compilation_envir.tsv"
  
rapid16s:
  man_protocol: "ProtocolSummaries/man_protocols/rapid16s.pdf"
  summary: "ProtocolSummaries/rapid16s_workflow_steps.html"

lsk:
  man_protocol: "ProtocolSummaries/man_protocols/lsk.pdf"
  summary: "ProtocolSummaries/lsk_workflow_steps.html"
  
notebooks:
  AMR: "Notebooks/Rich/"
  SA: "Notebooks/Azadmanesh/"
  TA: "Notebooks/Raad/"
  TSP: "Notebooks/Palacio/"
  DG: "Notebooks/Gill/"