default:
  global: "../GlobalScripts/"
  set_paths: "../GlobalScripts/set_paths.R"
  global_cols: "../GlobalScripts/reactable_columns.R"
  global_helpers: "../GlobalScripts/helper_functions.R"
  setup: "../GlobalScripts/global.R"
  conflicts: "../GlobalScripts/conflicts.R"
  inputs: "../../bioinformatics_stats/setup/global/inputs.R"
  data_functions: "../../bioinformatics_stats/setup/global/functions.R"
  fonts: "../../bioinformatics_stats/setup/global/fonts/FA6_Free-Solid-900.otf"
  
libprep:
  wd: "../LibraryPrep/"
  images: "../LibraryPrep/resources/images/"
  server: "../LibraryPrep/server/server.R"
  ui: "../LibraryPrep/ui/ui.R"
  tabs: "../LibraryPrep/ui/ui_tabs.R"
  steps: "../LibraryPrep/resources/steps.R"
  load_data: "../LibraryPrep/resources/load_data.R"
  workflow_vals: "../LibraryPrep/resources/workflow_vals.R"
  helper_functions: "../LibraryPrep/resources/helper_functions.R"
  col_defs: "../LibraryPrep/resources/colDefs.R"
  build_tables: "../LibraryPrep/server/build_tables.R"
  card_config: "../LibraryPrep/server/card_config.R"
  navigation: "../LibraryPrep/server/reactive_navigation.R"
  configure_workflow: "../LibraryPrep/server/configure_workflow.R"
  render_text: "../LibraryPrep/server/rendertext.R"
  record_log: "../LibraryPrep/server/record_log.R"
  calculations: "../LibraryPrep/server/calculations.R"
  setup_values: "../LibraryPrep/server/setup_values.R"
  report_template: "../templates/notebook_report.Rmd"
  
rapid16s:
  man_protocol: "../ProtocolSummaries/man_protocols/rapid16s.pdf"
  summary: "../ProtocolSummaries/rapid16s_workflow_steps.html"

lsk:
  man_protocol: "../ProtocolSummaries/man_protocols/lsk.pdf"
  summary: "../ProtocolSummaries/lsk_workflow_steps.html"
  
notebooks:
  AMR: "../Notebooks/Rich/"
  SA: "../Notebooks/Azadmanesh/"
  TA: "../Notebooks/Raad/"
  TSP: "../Notebooks/Palacio/"
  DG: "../Notebooks/Gill/"
  
loris:
  day1: "2023-10-26"
  last: "2024-10-25"
  metadata: 
    bristol: "../../bioinformatics_stats/metadata/loris/bristols.R"
    diet: "../../bioinformatics_stats/metadata/loris/diet_schedule.R"
    meds: "../../bioinformatics_stats/metadata/loris/meds_schedule.R"
    housing: "../../bioinformatics_stats/metadata/loris/housing.R"
    repro: "../../bioinformatics_stats/metadata/loris/repro_log.R"
    health: "../../bioinformatics_stats/metadata/loris/health_log.R"
    summary: "../../bioinformatics_stats/metadata/loris/samples_metadata.tsv"
    key: "../../bioinformatics_stats/metadata/loris/metadata_key.R"
    studbook: "../../data/subjects_loris.csv"
  extracts: "../../bioinformatics_stats/dataframes/sample_inventories/extracts_loris.tsv"
  libraries: "../../bioinformatics_stats/dataframes/sample_inventories/libraries_loris.tsv"
  samples: "../../bioinformatics_stats/dataframes/sample_inventories/samples_loris.tsv"
  compilation: "../../bioinformatics_stats/dataframes/sample_inventories/compilation_loris.tsv"
  libraries_csv: "../../data/libraries_loris.csv"
  seqruns_csv: "../../data/seqruns_loris.csv"
  compilation_csv: "../../data/compilation_loris.csv"
  extracts_csv: "../../data/extracts_loris.csv"
  samples_csv: "../../data/samples_loris.csv"
  outputs_wf16s: "../../bioinformatics_stats/data/loris/outputs_wf16s/"
  barcodes_output: "../../bioinformatics_stats/dataframes/barcodes/loris/"
  read_alignments: "../../bioinformatics_stats/data/loris/read_alignments"
  sample_sheet: "../../bioinformatics_stats/loris/dataframes/sample_sheet/"
  taxa_reps:
    aligned: "../../bioinformatics_stats/data/loris/taxonomy/refseqs_aligned.fasta"
    tree: "../../bioinformatics_stats/data/loris/taxonomy/refseqs_tree.newick"
    table: "../../bioinformatics_stats/data/loris/taxonomy/tax_table.tsv"
  abundance_wf16s: "../../bioinformatics_stats/data/loris/wf16s_abundance/"
  
bats:
  extracts: "../data_samples/extracts_bats.tsv"
  libraries: "../data_samples/libraries_bats.tsv"
  samples: "../data_samples/samples_bats.tsv"
  compilation: "../../bioinformatics_stats/dataframes/sample_inventories/compilation_bats.tsv"
  compilation_csv: "../../data/compilation_bats.csv"
  extracts_csv: "../../data/extracts_bats.csv"
  samples_csv: "../../data/samples_bats.csv"
  
marmoset:
  extracts: "../../bioinformatics_stats/dataframes/sample_inventories/extracts_marmoset.tsv"
  libraries: "../../bioinformatics_stats/dataframes/sample_inventories/libraries_marmoset.tsv"
  samples: "../../bioinformatics_stats/dataframes/sample_inventories/samples_marmoset.tsv"
  compilation: "../../bioinformatics_stats/dataframes/sample_inventories/compilation_marmoset.tsv"
  libraries_csv: "../../data/libraries_marmoset.csv"
  seqruns_csv: "../../data/seqruns_marmoset.csv"
  compilation_csv: "../../data/compilation_marmoset.csv"
  extracts_csv: "../../data/extracts_marmoset.csv"
  samples_csv: "../../data/samples_marmoset.csv"
  barcodes_output: "../../bioinformatics_stats/dataframes/barcodes/marmoset/"
  barcode_alignments: "minion_data/barcode_alignments/hdz/"
  sample_sheet: "../../bioinformatics_stats/marmoset/dataframes/sample_sheet/"
  taxonomy_list: "../../bioinformatics_stats/marmoset/dataframes/taxonomy_list/"
  
isolates:
  extracts: "../data_samples/extracts_isolates.tsv"
  libraries: "../data_samples/libraries_isolates.tsv"
  samples: "../data_samples/samples_isolates.tsv"
  compilation: "../../bioinformatics_stats/dataframes/sample_inventories/compilation_isolates.tsv"
  compilation_csv: "../../data/compilation_isolates.csv"
  extracts_csv: "../../data/extracts_isolates.csv"
  samples_csv: "../../data/samples_isolates.csv"
  
envir:
  extracts: "../data_samples/extracts_envir.tsv"
  libraries: "../data_samples/libraries_envir.tsv"
  samples: "../data_samples/samples_envir.tsv"
  compilation: "../../bioinformatics_stats/dataframes/sample_inventories/compilation_envir.tsv"
  compilation_csv: "../../data/compilation_envir.csv"
  extracts_csv: "../../data/extracts_envir.csv"
  samples_csv: "../../data/samples_envir.csv"
  
sample_sheets:
  compilations:
    loris:    "../../bioinformatics_stats/dataframes/sample_sheet/loris/hdz_combined_sample_sheet.csv"
    marmoset: "../../bioinformatics_stats/dataframes/sample_sheet/marmoset/cm_combined_sample_sheet.csv"
  hdz1:  "../../bioinformatics_stats/dataframes/sample_sheet/loris/hdz1_sample_sheet.csv"
  hdz2:  "../../bioinformatics_stats/dataframes/sample_sheet/loris/hdz2_sample_sheet.csv"
  hdz3:  "../../bioinformatics_stats/dataframes/sample_sheet/loris/hdz3_sample_sheet.csv"
  hdz4:  "../../bioinformatics_stats/dataframes/sample_sheet/loris/hdz4_sample_sheet.csv"
  hdz5:  "../../bioinformatics_stats/dataframes/sample_sheet/loris/hdz5_sample_sheet.csv"
  hdz6:  "../../bioinformatics_stats/dataframes/sample_sheet/loris/hdz6_sample_sheet.csv"
  hdz7:  "../../bioinformatics_stats/dataframes/sample_sheet/loris/hdz7_sample_sheet.csv"
  hdz8:  "../../bioinformatics_stats/dataframes/sample_sheet/loris/hdz8_sample_sheet.csv"
  hdz9:  "../../bioinformatics_stats/dataframes/sample_sheet/loris/hdz9_sample_sheet.csv"
  hdz10: "../../bioinformatics_stats/dataframes/sample_sheet/loris/hdz10_sample_sheet.csv"
  hdz11: "../../bioinformatics_stats/dataframes/sample_sheet/loris/hdz11_sample_sheet.csv"
  hdz12: "../../bioinformatics_stats/dataframes/sample_sheet/loris/hdz12_sample_sheet.csv"
  hdz13: "../../bioinformatics_stats/dataframes/sample_sheet/loris/hdz13_sample_sheet.csv"
  hdz14: "../../bioinformatics_stats/dataframes/sample_sheet/loris/hdz14_sample_sheet.csv"
  hdz15: "../../bioinformatics_stats/dataframes/sample_sheet/loris/hdz15_sample_sheet.csv"
  hdz16: "../../bioinformatics_stats/dataframes/sample_sheet/loris/hdz16_sample_sheet.csv"
  hdz17: "../../bioinformatics_stats/dataframes/sample_sheet/loris/hdz17_sample_sheet.csv"
  hdz18: "../../bioinformatics_stats/dataframes/sample_sheet/loris/hdz18_sample_sheet.csv"
  cm001: "../../bioinformatics_stats/dataframes/sample_sheet/marmoset/cm001_sample_sheet.csv"
  cm002: "../../bioinformatics_stats/dataframes/sample_sheet/marmoset/cm002_sample_sheet.csv"
  cm003: "../../bioinformatics_stats/dataframes/sample_sheet/marmoset/cm003_sample_sheet.csv"
  cm004: "../../bioinformatics_stats/dataframes/sample_sheet/marmoset/cm004_sample_sheet.csv"
  cm005: "../../bioinformatics_stats/dataframes/sample_sheet/marmoset/cm005_sample_sheet.csv"
  cm006: "../../bioinformatics_stats/dataframes/sample_sheet/marmoset/cm006_sample_sheet.csv"
  cm007: "../../bioinformatics_stats/dataframes/sample_sheet/marmoset/cm007_sample_sheet.csv"
  cm008: "../../bioinformatics_stats/dataframes/sample_sheet/marmoset/cm008_sample_sheet.csv"
  cm009: "../../bioinformatics_stats/dataframes/sample_sheet/marmoset/cm009_sample_sheet.csv"
  cm010: "../../bioinformatics_stats/dataframes/sample_sheet/marmoset/cm010_sample_sheet.csv"
  cm011: "../../bioinformatics_stats/dataframes/sample_sheet/marmoset/cm011_sample_sheet.csv"

barcode_alignments:
  compilations:
    loris: "minion_data/barcode_alignments/loris/hdz_combined_barcode_alignment.tsv"
    marmoset: "minion_data/barcode_alignments/marmoset/cm_combined_barcode_alignment.tsv"
  hdz1:  "minion_data/barcode_alignments/loris/hdz1_barcode_alignment.tsv"
  hdz2:  "minion_data/barcode_alignments/loris/hdz2_barcode_alignment.tsv"
  hdz3:  "minion_data/barcode_alignments/loris/hdz3_barcode_alignment.tsv"
  hdz4:  "minion_data/barcode_alignments/loris/hdz4_barcode_alignment.tsv"
  hdz5:  "minion_data/barcode_alignments/loris/hdz5_barcode_alignment.tsv"
  hdz6:  "minion_data/barcode_alignments/loris/hdz6_barcode_alignment.tsv"
  hdz7:  "minion_data/barcode_alignments/loris/hdz7_barcode_alignment.tsv"
  hdz8:  "minion_data/barcode_alignments/loris/hdz8_barcode_alignment.tsv"
  hdz9:  "minion_data/barcode_alignments/loris/hdz9_barcode_alignment.tsv"
  hdz10: "minion_data/barcode_alignments/loris/hdz10_barcode_alignment.tsv"
  hdz11: "minion_data/barcode_alignments/loris/hdz11_barcode_alignment.tsv"
  hdz12: "minion_data/barcode_alignments/loris/hdz12_barcode_alignment.tsv"
  hdz13: "minion_data/barcode_alignments/loris/hdz13_barcode_alignment.tsv"
  hdz14: "minion_data/barcode_alignments/loris/hdz14_barcode_alignment.tsv"
  hdz15: "minion_data/barcode_alignments/loris/hdz15_barcode_alignment.tsv"
  hdz16: "minion_data/barcode_alignments/loris/hdz16_barcode_alignment.tsv"
  hdz17: "minion_data/barcode_alignments/loris/hdz17_barcode_alignment.tsv"
  hdz18: "minion_data/barcode_alignments/loris/hdz18_barcode_alignment.tsv"
  cm001: "minion_data/barcode_alignments/marmoset/cm001_barcode_alignment.tsv"
  cm002: "minion_data/barcode_alignments/marmoset/cm002_barcode_alignment.tsv"
  cm003: "minion_data/barcode_alignments/marmoset/cm003_barcode_alignment.tsv"
  cm004: "minion_data/barcode_alignments/marmoset/cm004_barcode_alignment.tsv"
  cm005: "minion_data/barcode_alignments/marmoset/cm005_barcode_alignment.tsv"
  cm006: "minion_data/barcode_alignments/marmoset/cm006_barcode_alignment.tsv"
  cm007: "minion_data/barcode_alignments/marmoset/cm007_barcode_alignment.tsv"
  cm008: "minion_data/barcode_alignments/marmoset/cm008_barcode_alignment.tsv"
  cm009: "minion_data/barcode_alignments/marmoset/cm009_barcode_alignment.tsv"
  cm010: "minion_data/barcode_alignments/marmoset/cm010_barcode_alignment.tsv"
  cm011: "minion_data/barcode_alignments/marmoset/cm011_barcode_alignment.tsv"
  
methods_16s:
  libprep_workflow: "'rapid16s'"
  dorado_model: "'dna_r10.4.1_e8.2_400bps_sup@v5.0.0'"
  min_length: 1000
  max_length: 2000
  min_qual: 7
  min_id: 85
  min_cov: 80
  kit_name: "'SQK-16S114-24'"
  tax_rank: "S"
  n_taxa_barplot: 12
  abund_threshold: 0
  loris:
    rarefy: 5000
    norm: "SRS"
    min_abund: 0.0001
    min_freq: 0.02
    inlcude_lowest: TRUE
    unifrac: TRUE
    betadiv: "canberra"
    tax4fun_db: "Ref99NR"
    loris_rarefy: 5000
    keg_minID: 97
  loris_norm: "SRS"
  loris_filter:
    rel_abund: 0.0001
    freq: 0.02
    inlcude_lowest: TRUE

