extraction <- list(
  protocols = list(
    cultBacBash = list(
      "name"          = "Bacterial Culture Bead Bashing",
      "N"             = 24,
      "sample"        = "culture",
      "stabilizer"    = "none",
      "target"        = "microbial",
      "molecule"      = "DNA",
      "lysis"         = "bead_bashing",
      "isolation"     = "spin_column",
      "eluate_ul"     = 50,
      "yield_ug"      = 25,
      "input_ul"      = 200,
      "inhib_removal" = "included",
      "kit"           = FecalMini,
      "extras"        = chloramphenicol
    ),
    colBacRapid = list(
      "name"          = "Bacterial Colony Rapid",
      "N"             = 24,
      "sample"        = "colony_plated",
      "stabilizer"    = "none",
      "target"        = "microbial",
      "molecule"      = "DNA",
      "lysis"         = "enzyme",
      "isolation"     = "none",
      "eluate_ul"     = 50,
      "yield_ug"      = 25,
      "input_ul"      = 50,
      "inhib_removal" = "not needed",
      "kit"           = ProteinaseK,
      "extras"        = NULL
    ),
    colBacMDA = list(
      "name"          = "Bacterial Colony Direct to MDA",
      "N"             = 24,
      "sample"        = "colony_plated",
      "stabilizer"    = "none",
      "target"        = "microbial",
      "molecule"      = "DNA",
      "lysis"         = "chemical",
      "isolation"     = "none",
      "eluate_ul"     = 36,
      "yield_ug"      = 5,
      "input_ul"      = 4,
      "inhib_removal" = "not needed",
      "kit"           = scREPLI,
      "extras"        = NULL
    ),
    culBacMDA = list(
      "name"          = "Bacterial Culture Direct to MDA",
      "N"             = 24,
      "sample"        = "culture_liquid",
      "stabilizer"    = "PBS",
      "target"        = "microbial",
      "molecule"      = "DNA",
      "lysis"         = "chemical",
      "isolation"     = "none",
      "eluate_ul"     = 36,
      "yield_ug"      = 5,
      "input_ul"      = 4,
      "inhib_removal" = "not needed",
      "kit"           = scREPLI,
      "extras"        = NULL
    ),
    fecBacBash = list(
      "name"          = "Fecal Microbiome Bead Bashing",
      "N"             = 24,
      "sample"        = "feces",
      "stabilizer"    = "DNA/RNA Shield",
      "target"        = "microbial",
      "molecule"      = "DNA",
      "lysis"         = "bead_bashing",
      "isolation"     = "spin_column",
      "eluate_ul"     = 50,
      "yield_ug"      = 25,
      "input_ul"      = 1000,
      "inhib_removal" = "included",
      "kit"           = FecalMini,
      "extras"        = NULL
    ),
    fecHostBash = list(
      "name"          = "Fecal Host DNA Bead Bashing",
      "N"             = 24,
      "sample"        = "feces",
      "stabilizer"    = "DNA/RNA Shield",
      "target"        = "host",
      "molecule"      = "DNA",
      "lysis"         = "bead_bashing",
      "isolation"     = "spin_column",
      "eluate_ul"     = 50,
      "yield_ug"      = 25,
      "input_ul"      = 1000,
      "inhib_removal" = "included",
      "kit"           = FecalMini,
      "extras"        = NULL
    ),
    fecMag = list(
      "name"          = "Fecal MagBead DNA + RNA Fractions",
      "N"             = 24,
      "sample"        = "feces",
      "stabilizer"    = "DNA/RNA Shield",
      "target"        = "host",
      "molecule"      = c("DNA", "RNA"),
      "lysis"         = "chemical",
      "isolation"     = "magBead",
      "eluate_ul"     = 50,
      "yield_ug"      = 15,
      "input_ul"      = 200,
      "inhib_removal" = "separate",
      "kit"           = TotalMagMini,
      "extras"        = NULL
    ),
    fecHMW = list(
      "name"          = "Fecal MagBead HMW DNA",
      "N"             = 24,
      "sample"        = "feces",
      "stabilizer"    = "DNA/RNA Shield",
      "target"        = c("host", "microbial"),
      "molecule"      = "DNA",
      "lysis"         = "enzyme",
      "isolation"     = "magBead",
      "eluate_ul"     = 50,
      "yield_ug"      = 10,
      "input_ul"      = 400,
      "inhib_removal" = "separate",
      "kit"           = DNAMagHMW,
      "extras"        = NULL
    ),
    culHMW = list(
      "name"          = "Bacterial Culture MagBead HMW DNA",
      "N"             = 24,
      "sample"        = "culture",
      "stabilizer"    = "none",
      "target"        = "microbial",
      "molecule"      = "DNA",
      "lysis"         = "enzyme",
      "isolation"     = "magBead",
      "eluate_ul"     = 50,
      "yield_ug"      = 10,
      "input_ul"      = 200,
      "inhib_removal" = "separate",
      "kit"           = DNAMagHMW,
      "extras"        = NULL
    )
  ),
  kits = list(
    FecalMini = list(
      "name"    = "Quick-DNA Fecal/Soil Microbe Miniprep Kit",
      "catalog" = "D6010",
      "cost"    = 264.90,
      "rxns"    = 50
    ),
    TotalMagMini = list(
      "name"    = "Quick-DNA/RNA MagBead",
      "catalog" = "R2130",
      "cost"    = 418.90,
      "rxns"    = 96
    ),
    DNAMagHMW = list(
      "name"    = "Quick-DNA HMW MagBead Kit",
      "catalog" = "D6060",
      "cost"    = 320.90,
      "rxns"    = 96
    ),
    scREPLI = list(
      "name"         = "REPLI-g Single Cell Kit",
      "manufacturer" = "Qiagen",
      "catalog"      = "150343",
      "cost"         = 840,
      "rxns"         = 24
    )
  )
)
