---
title: "Lab Notebook Entry - Library Prep"
author: "`r params$author` with assist by `r params$assists`"
date: "`r params$date`"
output: 
  html_document:
    code_download: false
    toc: false
    toc_location: "before"
    toc_depth: 4
    number_sections: false
    toc_float: true
    code_folding: "hide"
    fig_caption: true
params:
    setup: NA
    step_data: NA
    steps: NA
    libprep: NA
    libraries: NA
    extracts: NA
    rxns: NA
    
---


```{r include=FALSE}
opts_chunk$set(message = FALSE,
               warning = FALSE,
               echo    = FALSE,
               include = TRUE,
               eval    = TRUE)

library(knitr)
library(bookdown)
library(conflicted)
library(devtools)
library(dplyr)
library(gt)
library(gtExtras)
library(gtable)
library(htmltools)
library(kableExtra)
library(lubridate)
library(paletteer)
library(pandoc)
library(readr) 
library(tibble)
library(tidyr)
library(usethis)
library(xfun)
```

```{r}
samples <-  case_when(
    params$sampleset == "loris"    ~ "Pygmy Loris DNA Extracts (Feces)",
    params$sampleset == "marmoset" ~ "Marmoset DNA Extracts (Feces)",
    params$sampleset == "bat_wild" ~ "Bat DNA Extracts (Feces)",
    params$sampleset == "envir"    ~ "DNA Extracts from Environmental Sampling",
    params$sampleset == "isolates" ~ "Purified DNA from Bacterial Isolates",
  )

```


```{r}
tagList(tags$h1(paste(params$libprep$LibPrepWorkflow)),
        tags$h2(paste("Starting from ", samples)))
```


## Summary

```{r}
tagList(
  tags$h3(paste0("ID Code for Sequencing Run: "    , params$LibraryCode)),
  tags$h4(paste0("Total Libraries Prepped: "       , params$n_rxns)),
  tags$em(paste0("Number of Negative Controls: "   , params$n_controls))
)

as_tibble(params$libprep) %>%
  select(
    TubeNo,
    SequenceID,
    SampleID,
    CollectionDate,
    Subject,
    n_dna_extractions,
    n_rna_extractions,
    n_seq_16s) %>%
  gt() %>%
  cols_label(
    LibraryTube        ~ "Tube Label",
    SequenceID         ~ "Sequenced Library ID",
    SampleID           ~ "Sample ID",
    CollectionDate     ~ "Date of Sample Collection",
    Subject            ~ "Subject Name",
    n_dna_extractions  ~ "DNA Extracts",
    n_rna_extractions  ~ "RNA Extracts",
    n_seq_16s          ~ "16S Libraries"
  ) %>%
  tab_spanner(label = "N Completed per Sample", columns = c("n_dna_extractions",
                                                            "n_rna_extractions",
                                                            "n_seq_16s")) %>%
  fmt_date(columns = CollectionDate) %>%
  opt_stylize(6, "pink")
```


### Reaction Volumes

```{r}
as_tibble(params$rxns) %>%
  select(-N) %>%
  gt(rowname_col = "Reagent", groupname_col = "step") %>%
  cols_label(
    Volume_rxn   ~ "Volume per rxn (ul)",
    Volume_total ~ "Total Volume (ul)"
  ) %>%
  summary_rows(columns = c("Volume_rxn", "Volume_total"), fns = "sum") %>%
  fmt_units()  %>%
  opt_stylize(6, "pink")
```

### Quality Control Results

```{r}
as_tibble(params$QC) %>%
  gt() %>%
  cols_label(
    TubeNo      ~ "Tube Label",
    ExtractID   ~ "DNA Extract ID",
    ExtractConc ~ "Initial Extract Concentration (ng/ul)",
    LibQC1      ~ "Concentration after Endprep (ng/ul)",
    LibQC2      ~ "Concentration after Adapter Ligation (ng/ul)"
  ) %>%
  fmt_units()  %>%
  opt_stylize(6, "pink")
```




## Procedure Steps and Notes

```{r}
steps <- as.list(params$steps)


tagList(
        tags$blockquote(params$setup_note),
        tags$ol(
          lapply(steps, function(step) {
            tagList(
            tags$li(step$detail),
            tags$p(step$timestamp),
            if (!is.null(step$note)) tags$blockquote(step$note),
            tags$hr()
            )
          })
        ),
        tags$blockquote(params$conclusion_note)
      )
```
